PREFIX base:        <http://opencaesar.io/tutorial/vocabulary/base#>
PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#>

SELECT DISTINCT ?i1_id ?i2_id

WHERE {
 GRAPH ?l2 { ?j a [] }
 VALUES ?l2 {
    <http://opencaesar.io/tutorial/description/L2-end-to-end-lander-operations>
    <http://opencaesar.io/tutorial/description/L2-end-to-end-orbiter-operations>
    <http://opencaesar.io/tutorial/description/L2-shared-operations> 
  }
  ?j a mission:Junction ;
    mission:joins1 [
      a mission:Interface ;
      base:hasIdentifier ?i1_id
    ] ;
    mission:joins2 [
      a mission:Interface ;
      base:hasIdentifier ?i2_id
    ]
}