PREFIX dc:          <http://purl.org/dc/elements/1.1/>
PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#>

SELECT DISTINCT ?obj ?desc

WHERE {
	?obj 
      a mission:Objective ;
      dc:description ?desc .
}
ORDER BY ?obj
