PREFIX base:        <http://opencaesar.io/tutorial/vocabulary/base#>
PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#>

SELECT DISTINCT ?o_id ?o_name

WHERE {
	?obj 
      a mission:Objective ;
      base:hasIdentifier ?o_id ;
      base:hasCanonicalName ?o_name ;
}
ORDER BY ?o_id
